# Generated by Django 4.2.6 on 2024-01-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('action', models.CharField(max_length=120, verbose_name='действие')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='время начала выполнения')),
                ('place', models.CharField(max_length=75, verbose_name='место')),
                ('is_pleasant', models.BooleanField(blank=True, default=False, null=True, verbose_name='признак приятной привычки')),
                ('periodicity', models.IntegerField(blank=True, null=True, verbose_name='периодичность')),
                ('award', models.CharField(blank=True, max_length=75, null=True, verbose_name='вознаграждение')),
                ('time_to_complete', models.IntegerField(blank=True, null=True, verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(blank=True, default=False, null=True, verbose_name='признак публичности')),
                ('related_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
