# Generated by Django 4.2.6 on 2024-01-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_related_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.IntegerField(blank=True, default=120, null=True, verbose_name='время на выполнение'),
        ),
    ]
