# Generated by Django 4.2.6 on 2024-01-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_time_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.IntegerField(blank=True, null=True, verbose_name='время на выполнение'),
        ),
    ]
