# Generated by Django 4.2.6 on 2024-01-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_time_to_complete_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='время начала выполнения'),
        ),
    ]
